ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS fee_amount FLOAT8 NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fee_rate   FLOAT8 NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fee_chain  TEXT   NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS fee_wallet TEXT   NOT NULL DEFAULT '';
