UPDATE balances
SET demo_naira = 10000
WHERE email IN (
  'carsonpine@hotmail.com',
  'quaddavid4@hotmail.com',
  'vant.charlie@testmail.com',
  'vant.diana@testmail.com',
  'vant.eve@testmail.com',
  'vant.frank@testmail.com',
  'vant.grace@testmail.com',
  'vant.henry@testmail.com',
  'vant.iris@testmail.com',
  'vant.jack@testmail.com',
  'vant.lily@testmail.com',
  'vant.max@testmail.com',
  'vant.nina@testmail.com',
  'vant.omar@testmail.com',
  'vant.paul@testmail.com',
  'vant.quinn@testmail.com',
  'vant.rose@testmail.com',
  'vant.sam@testmail.com',
  'vant.tina@testmail.com',
  'vant.uma@testmail.com',
  'vant.victor@testmail.com',
  'vant.wendy@testmail.com',
  'vant.xander@testmail.com',
  'vant.yara@testmail.com',
  'vant.zack@testmail.com',
  'vant.amber@testmail.com',
  'vant.blake@testmail.com',
  'vant.cora@testmail.com',
  'vant.derek@testmail.com',
  'vant.elena@testmail.com'
);
